type Product={id:number;name:string;description?:string;price:number;stock:number;category:string;image_url?:string;promotion?:boolean;discount_percent?:number;active?:boolean};
type Order={id:number;reference?:string;customer?:any;total?:number;payment_method?:string;status?:string;created_at?:string};
const API='http://localhost:5000/api/products', ORDERS='http://localhost:5000/api/orders';
let products:Product[]=[],orders:Order[]=[];
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
const money=(n:number)=>`${Number(n||0).toFixed(0)} DH`;
async function load(){try{const [p,o]=await Promise.all([fetch(API),fetch(ORDERS)]);products=p.ok?await p.json():[];orders=o.ok?await o.json():[]}catch{products=[];orders=[]}}
const main=()=>document.querySelector('.x-admin>main') as HTMLElement|null;
function top(title:string,sub:string,add=false){return `<div class="admin-topbar"><div></div><div class="admin-user"><span>H</span><b>Admin</b><i>⌄</i></div></div><header class="admin-hero"><div class="admin-hero-icon">▢</div><div><h1>${title}</h1><p>${sub}</p></div>${add?'<button data-admin-add>＋ Ajouter un produit</button>':'<button data-safe-shop>Voir espace client</button>'}</header>`}
function shell(title:string,body:string,sub='Espace de gestion OSRAH Cosmétiques.',add=false){return `<div class="admin-page">${top(title,sub,add)}${body}</div>`}
function kpi(label:string,value:any,kind='pink'){return `<div class="admin-kpi ${kind}"><i></i><div><b>${value}</b><small>${label}</small></div></div>`}
function dashboard(){const ca=orders.reduce((s,o)=>s+Number(o.total||0),0);return shell('Tableau de bord',`<section class="admin-kpis">${kpi('Produits',products.length)}${kpi('Commandes',orders.length,'green')}${kpi("Chiffre d'affaires",money(ca),'orange')}${kpi('Clients',new Set(orders.map(o=>o.customer?.email).filter(Boolean)).size)}</section>`,'Bienvenue dans votre espace de gestion OSRAH Cosmétiques.')}
function productRow(p:Product){const d=Math.max(1,Math.min(90,Number(p.discount_percent)||20));return `<tr data-product-row data-name="${esc(p.name.toLowerCase())}" data-category="${esc(p.category)}" data-promo="${p.promotion?'yes':'no'}"><td><div class="admin-prod"><div class="admin-prod-img">${p.image_url?`<img src="${esc(p.image_url)}" onerror="this.parentElement.innerHTML='✦'">`:'✦'}</div><div><b>${esc(p.name)}</b><small>${esc(p.description||'Produit OSRAH Cosmétiques')}</small></div></div></td><td>${esc(p.category||'—')}</td><td>${money(p.price)}</td><td><b class="${p.stock<=5?'stock-low':'stock-ok'}">${p.stock}</b></td><td><div class="promo-control"><button type="button" class="promo-switch ${p.promotion?'on':''}" data-safe-promo="${p.id}" title="Activer/désactiver la promotion"><i></i></button>${p.promotion?`<button type="button" class="promo-percent" data-safe-discount="${p.id}">-${d}%</button>`:''}</div></td><td><span class="status-active">● &nbsp;Actif</span></td><td><button type="button" class="admin-edit icon-action" data-safe-edit="${p.id}">✎</button><button type="button" class="admin-delete icon-action" data-safe-delete="${p.id}">▢</button></td></tr>`}
function productsView(){const total=products.length,stock=products.filter(p=>p.stock>5).length,low=products.filter(p=>p.stock<=5).length,promos=products.filter(p=>p.promotion).length;const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];return shell('Produits',`<section class="admin-kpis">${kpi('Produits au total',total)}${kpi('En stock',stock,'green')}${kpi('Stock faible',low,'orange')}${kpi('En promotion',promos)}</section><section class="admin-products-card"><div class="admin-toolbar"><input data-admin-search placeholder="⌕  Rechercher un produit..."><select data-admin-category><option value="">Toutes les catégories</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select data-admin-status><option>Tous les statuts</option><option>Actif</option></select><select data-admin-promo><option value="">Toutes les promotions</option><option value="yes">En promotion</option><option value="no">Sans promotion</option></select><button data-admin-reset>Réinitialiser</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Produit</th><th>Catégorie</th><th>Prix</th><th>Stock</th><th>Promo</th><th>Statut</th><th>Actions</th></tr></thead><tbody>${products.map(productRow).join('')}</tbody></table></div></section>`,'Gérez vos produits et mettez en avant vos offres spéciales.',true)}
function formView(p?:Product){return shell(p?'Modifier le produit':'Ajouter un produit',`<section class="admin-products-card"><form class="admin-form" data-safe-form data-id="${p?.id||''}"><label>Nom<input name="name" required value="${esc(p?.name||'')}"></label><label>Catégorie<input name="category" value="${esc(p?.category||'')}"></label><label>Prix (DH)<input name="price" type="number" min="0" required value="${p?.price??''}"></label><label>Stock<input name="stock" type="number" min="0" required value="${p?.stock??''}"></label><label>Promotion<select name="promotion"><option value="false" ${!p?.promotion?'selected':''}>Non</option><option value="true" ${p?.promotion?'selected':''}>Oui</option></select></label><label>Réduction (%)<input name="discount_percent" type="number" min="0" max="90" value="${p?.discount_percent??20}"></label><label class="full">Image URL<input name="image_url" value="${esc(p?.image_url||'')}"></label><label class="full">Description<textarea name="description">${esc(p?.description||'')}</textarea></label><div class="admin-form-actions"><button class="admin-primary">Enregistrer</button></div></form></section>`,'Renseignez les informations du produit.')}
function categoriesView(){const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];return shell('Catégories',`<section class="admin-products-card admin-category-grid">${cats.map(c=>`<article><i>◇</i><div><b>${esc(c)}</b><small>${products.filter(p=>p.category===c).length} produits</small></div></article>`).join('')}</section>`,'Organisez votre catalogue par catégories.')}
function ordersView(){return shell('Commandes',`<section class="admin-products-card"><table class="admin-table"><thead><tr><th>Commande</th><th>Client</th><th>Total</th><th>Paiement</th><th>Statut</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${esc(o.reference||`OSR-${o.id}`)}</td><td>${esc(o.customer?.name||'Client OSRAH')}</td><td>${money(o.total||0)}</td><td>${esc(o.payment_method||'—')}</td><td><span class="status-active">${esc(o.status||'Nouvelle')}</span></td></tr>`).join('')}</tbody></table></section>`,'Suivez les commandes de vos clients.')}
function clientsView(){const map=new Map();orders.forEach(o=>{const k=o.customer?.email||o.customer?.name;if(k)map.set(k,o.customer)});return shell('Clients',`<section class="admin-products-card">${[...map.values()].map(c=>`<div class="admin-list-row"><div><b>${esc(c.name||'Client OSRAH')}</b><small>${esc(c.email||'')} · ${esc(c.city||'')}</small></div><span class="status-active">Client</span></div>`).join('')||'<div class="admin-empty">Aucun client pour le moment.</div>'}</section>`,'Consultez les informations de vos clients.')}
function statsView(){const ca=orders.reduce((s,o)=>s+Number(o.total||0),0);return shell('Statistiques',`<section class="admin-kpis">${kpi("Chiffre d'affaires",money(ca))}${kpi('Panier moyen',money(orders.length?ca/orders.length:0),'green')}${kpi('Commandes',orders.length,'orange')}${kpi('Produits',products.length)}</section>`,'Analysez les performances de votre boutique.')}
function promotionsView(){return shell('Promotions',`<section class="admin-products-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Produit</th><th>Prix</th><th>Réduction</th><th>Promotion</th></tr></thead><tbody>${products.map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.promotion?`-${p.discount_percent||20}%`:'—'}</td><td><button type="button" class="promo-switch ${p.promotion?'on':''}" data-safe-promo="${p.id}"><i></i></button></td></tr>`).join('')}</tbody></table></div></section>`,'Activez vos offres spéciales et choisissez leur réduction.')}
const views:any={dashboard,products:productsView,add:()=>formView(),categories:categoriesView,orders:ordersView,clients:clientsView,stats:statsView,promotions:promotionsView};
async function show(name:string){await load();const m=main();if(!m)return;m.innerHTML=(views[name]||dashboard)();decorateSidebar(name)}
function decorateSidebar(active='dashboard'){const aside=document.querySelector('.x-admin>aside') as HTMLElement|null;if(!aside)return;aside.classList.add('osrah-admin-sidebar');aside.querySelectorAll(':scope>button:not(.last)').forEach(b=>b.remove());const logout=aside.querySelector('.last');const nav=[['dashboard','⌂','Tableau de bord'],['products','▣','Produits'],['categories','▤','Catégories'],['orders','▧','Commandes'],['clients','♧','Clients'],['stats','▥','Statistiques'],['promotions','◇','Promotions'],['settings','⚙','Paramètres']];nav.forEach(([key,icon,label])=>{const b=document.createElement('button');b.type='button';b.dataset.adminNav=key;b.className=key===active?'admin-on':'';b.innerHTML=`<i>${icon}</i><span>${label}</span>`;aside.insertBefore(b,logout)});if(!aside.querySelector('.admin-side-note')){const n=document.createElement('div');n.className='admin-side-note';n.innerHTML='<b>♕</b><span>Prendre soin<br>de votre beauté<br>au quotidien</span><em>♧</em>';aside.insertBefore(n,logout)}}
async function setPromo(p:Product,on:boolean,discount=p.discount_percent||20){const r=await fetch(`${API}/${p.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,promotion:on,discount_percent:discount,active:p.active!==false})});if(!r.ok)throw new Error('promo');}
function filters(){const q=(document.querySelector<HTMLInputElement>('[data-admin-search]')?.value||'').toLowerCase(),cat=document.querySelector<HTMLSelectElement>('[data-admin-category]')?.value||'',promo=document.querySelector<HTMLSelectElement>('[data-admin-promo]')?.value||'';document.querySelectorAll<HTMLElement>('[data-product-row]').forEach(r=>r.style.display=(!q||r.dataset.name?.includes(q))&&(!cat||r.dataset.category===cat)&&(!promo||r.dataset.promo===promo)?'':'none')}
document.addEventListener('click',async e=>{const t=e.target as HTMLElement;if(!t)return;const nav=t.closest('[data-admin-nav]') as HTMLElement|null;if(nav){e.preventDefault();e.stopImmediatePropagation();const key=nav.dataset.adminNav!;if(key==='settings'){alert('Paramètres OSRAH');return}await show(key);return}if(!t.closest('.x-admin'))return;const add=t.closest('[data-admin-add]');if(add){e.preventDefault();e.stopImmediatePropagation();await show('add');return}const sw=t.closest('[data-safe-promo]') as HTMLElement|null;if(sw){e.preventDefault();e.stopImmediatePropagation();const p=products.find(x=>x.id===Number(sw.dataset.safePromo));if(!p)return;sw.classList.toggle('loading');try{await setPromo(p,!p.promotion);await show(document.querySelector('[data-admin-nav].admin-on')?.getAttribute('data-admin-nav')==='promotions'?'promotions':'products')}catch{alert('Le bouton promotion ne peut pas se connecter au backend. Vérifiez que node server/server.js reste ouvert.')}return}const dis=t.closest('[data-safe-discount]') as HTMLElement|null;if(dis){e.preventDefault();e.stopImmediatePropagation();const p=products.find(x=>x.id===Number(dis.dataset.safeDiscount));if(!p)return;const v=prompt('Réduction (%)',String(p.discount_percent||20));if(v===null)return;await setPromo(p,true,Math.max(1,Math.min(90,Number(v)||20)));await show('products');return}const edit=t.closest('[data-safe-edit]') as HTMLElement|null;if(edit){const p=products.find(x=>x.id===Number(edit.dataset.safeEdit));const m=main();if(p&&m)m.innerHTML=formView(p);return}const del=t.closest('[data-safe-delete]') as HTMLElement|null;if(del){if(confirm('Supprimer ce produit ?')){await fetch(`${API}/${del.dataset.safeDelete}`,{method:'DELETE'});await show('products')}return}if(t.closest('[data-admin-reset]')){document.querySelectorAll<HTMLInputElement>('[data-admin-search]').forEach(x=>x.value='');document.querySelectorAll<HTMLSelectElement>('[data-admin-category],[data-admin-promo]').forEach(x=>x.value='');filters();return}},true);
document.addEventListener('input',e=>{if((e.target as HTMLElement).matches('[data-admin-search],[data-admin-category],[data-admin-promo]'))filters()},true);
document.addEventListener('change',e=>{if((e.target as HTMLElement).matches('[data-admin-category],[data-admin-promo]'))filters()},true);
document.addEventListener('submit',async e=>{const f=(e.target as HTMLElement).closest('[data-safe-form]') as HTMLFormElement|null;if(!f)return;e.preventDefault();const d=new FormData(f),id=f.dataset.id,body={name:String(d.get('name')||''),category:String(d.get('category')||''),price:Number(d.get('price')||0),stock:Number(d.get('stock')||0),promotion:String(d.get('promotion'))==='true',discount_percent:Number(d.get('discount_percent')||0),image_url:String(d.get('image_url')||''),description:String(d.get('description')||''),active:true};const r=await fetch(id?`${API}/${id}`:API,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){alert('Impossible d’enregistrer le produit.');return}await show('products')},true);
window.addEventListener('load',()=>setTimeout(()=>decorateSidebar('dashboard'),120));
export {};