type Product={id:number;name:string;description?:string;price:number;stock:number;category:string;image_url?:string};
type Order={id:number;reference?:string;customer?:any;items?:any[];total?:number;payment_method?:string;status?:string;created_at?:string};
const API='http://localhost:5000/api/products';
const ORDERS='http://localhost:5000/api/orders';
const money=(n:number)=>`${Number(n||0).toFixed(0)} DH`;
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
let products:Product[]=[];
let orders:Order[]=[];
async function load(){try{const [p,o]=await Promise.all([fetch(API),fetch(ORDERS)]);products=p.ok?await p.json():[];orders=o.ok?await o.json():[]}catch{products=[];orders=[]}}
function main(){return document.querySelector('.x-admin>main') as HTMLElement|null}
function shell(title:string,body:string){return `<header><div><h1>${title}</h1><p>Espace de gestion OSRAH Cosmétiques.</p></div><button data-safe-shop>Voir espace client</button></header>${body}`}
function dashboard(){return shell('Dashboard',`<section class="x-stats"><div><span>Produits</span><b>${products.length}</b></div><div><span>Commandes</span><b>${orders.length}</b></div><div><span>Chiffre d'affaires</span><b>${money(orders.reduce((s,o)=>s+Number(o.total||0),0))}</b></div><div><span>Clients</span><b>${new Set(orders.map(o=>o.customer?.email).filter(Boolean)).size}</b></div></section>`)}
function productsView(){return shell('Produits',`<section style="padding:24px"><div class="admin-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Produit</th><th>Catégorie</th><th>Prix</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${products.map(p=>`<tr><td><div class="admin-prod"><img src="${esc(p.image_url||'')}"><div><b>${esc(p.name)}</b><small>${esc(p.description||'')}</small></div></div></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="admin-edit" data-safe-edit="${p.id}">Modifier</button><button class="admin-delete" data-safe-delete="${p.id}">Supprimer</button></td></tr>`).join('')}</tbody></table></div></div></section>`)}
function addView(p?:Product){return shell(p?'Modifier produit':'Ajouter produit',`<section style="padding:24px"><div class="admin-card"><form class="admin-form" data-safe-form data-id="${p?.id||''}"><label>Nom<input name="name" required value="${esc(p?.name||'')}"></label><label>Catégorie<input name="category" value="${esc(p?.category||'')}"></label><label>Prix (DH)<input name="price" type="number" min="0" step="0.01" required value="${p?.price??''}"></label><label>Stock<input name="stock" type="number" min="0" required value="${p?.stock??''}"></label><label class="full">Image URL<input name="image_url" value="${esc(p?.image_url||'')}"></label><label class="full">Description<textarea name="description">${esc(p?.description||'')}</textarea></label><div class="admin-form-actions"><button class="admin-primary" type="submit">Enregistrer</button></div></form></div></section>`)}
function ordersView(){return shell('Commandes',`<section style="padding:24px"><div class="admin-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Commande</th><th>Client</th><th>Total</th><th>Paiement</th><th>Statut</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${esc(o.reference||`OSR-${o.id}`)}</b><small>${o.created_at?new Date(o.created_at).toLocaleString('fr-FR'):''}</small></td><td>${esc(o.customer?.name||'Client OSRAH')}</td><td>${money(o.total||0)}</td><td>${esc(o.payment_method||'')}</td><td>${esc(o.status||'Nouvelle')}</td></tr>`).join('')}</tbody></table></div></div></section>`)}
function clientsView(){const map=new Map<string,any>();orders.forEach(o=>{const e=o.customer?.email||o.customer?.phone||o.customer?.name;if(e)map.set(e,o.customer)});return shell('Clients',`<section style="padding:24px"><div class="admin-card">${[...map.values()].map(c=>`<div class="admin-list-row"><div><b>${esc(c.name||'Client OSRAH')}</b><small>${esc(c.email||'')} ${esc(c.city||'')}</small></div><span class="admin-badge">Client</span></div>`).join('')||'<div class="admin-empty">Aucun client pour le moment.</div>'}</div></section>`)}
function statsView(){const ca=orders.reduce((s,o)=>s+Number(o.total||0),0);const avg=orders.length?ca/orders.length:0;return shell('Statistiques',`<section class="x-stats"><div><span>Chiffre d'affaires</span><b>${money(ca)}</b></div><div><span>Panier moyen</span><b>${money(avg)}</b></div><div><span>Commandes</span><b>${orders.length}</b></div><div><span>Produits</span><b>${products.length}</b></div></section>`)}
async function show(name:string){const m=main();if(!m)return;await load();if(name==='products')m.innerHTML=productsView();else if(name==='add')m.innerHTML=addView();else if(name==='orders')m.innerHTML=ordersView();else if(name==='clients')m.innerHTML=clientsView();else if(name==='stats')m.innerHTML=statsView();else m.innerHTML=dashboard()}
document.addEventListener('click',async e=>{const t=e.target as HTMLElement|null;if(!t)return;const admin=t.closest('.x-admin');if(!admin)return;const side=t.closest(':scope > button');if(side&&side.parentElement?.matches('.x-admin>aside')){const buttons=Array.from(side.parentElement.querySelectorAll('button'));const i=buttons.indexOf(side as HTMLButtonElement);const names=['dashboard','products','add','orders','clients','stats'];if(i>=0&&i<6){e.preventDefault();await show(names[i]);return}}
 if(t.closest('[data-safe-shop]')){const buttons=document.querySelectorAll('.x-admin>main header button');(buttons[0] as HTMLButtonElement|null)?.click();return}
 const edit=t.closest('[data-safe-edit]') as HTMLElement|null;if(edit){const p=products.find(x=>x.id===Number(edit.dataset.safeEdit));const m=main();if(p&&m)m.innerHTML=addView(p);return}
 const del=t.closest('[data-safe-delete]') as HTMLElement|null;if(del){if(!confirm('Supprimer ce produit ?'))return;await fetch(`${API}/${del.dataset.safeDelete}`,{method:'DELETE'}).catch(()=>{});await show('products');return}
},true);
document.addEventListener('submit',async e=>{const form=(e.target as HTMLElement)?.closest('[data-safe-form]') as HTMLFormElement|null;if(!form)return;e.preventDefault();const fd=new FormData(form);const id=form.dataset.id;const body={name:String(fd.get('name')||''),category:String(fd.get('category')||''),price:Number(fd.get('price')||0),stock:Number(fd.get('stock')||0),image_url:String(fd.get('image_url')||''),description:String(fd.get('description')||'')};const r=await fetch(id?`${API}/${id}`:API,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).catch(()=>null);if(!r||!r.ok){alert('Impossible d’enregistrer. Vérifiez le backend.');return}await show('products')},true);
