type Product={id:number;name:string;description?:string;price:number;stock:number;category:string;image_url?:string;promotion?:boolean;discount_percent?:number;active?:boolean};
type Order={id:number;reference?:string;customer?:any;items?:any[];total?:number;payment_method?:string;status?:string;created_at?:string};
const API='http://localhost:5000/api/products';
const ORDERS='http://localhost:5000/api/orders';
const money=(n:number)=>`${Number(n||0).toFixed(0)} DH`;
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
let products:Product[]=[];let orders:Order[]=[];
async function load(){try{const [p,o]=await Promise.all([fetch(API),fetch(ORDERS)]);products=p.ok?await p.json():[];orders=o.ok?await o.json():[]}catch{products=[];orders=[]}}
function main(){return document.querySelector('.x-admin>main') as HTMLElement|null}
function shell(title:string,body:string,subtitle='Espace de gestion OSRAH Cosmétiques.'){return `<div class="admin-page"><header class="admin-hero"><div class="admin-hero-icon">▣</div><div><h1>${title}</h1><p>${subtitle}</p></div><button data-safe-shop>Voir espace client</button></header>${body}</div>`}
function dashboard(){return shell('Tableau de bord',`<section class="admin-kpis"><div class="admin-kpi"><small>Produits</small><b>${products.length}</b><span>au total</span></div><div class="admin-kpi"><small>Commandes</small><b>${orders.length}</b><span>enregistrées</span></div><div class="admin-kpi"><small>Chiffre d'affaires</small><b>${money(orders.reduce((s,o)=>s+Number(o.total||0),0))}</b><span>cumulé</span></div><div class="admin-kpi"><small>Clients</small><b>${new Set(orders.map(o=>o.customer?.email).filter(Boolean)).size}</b><span>uniques</span></div></section>`,'Bienvenue dans votre espace de gestion OSRAH Cosmétiques.')}
function productsView(){
 const total=products.length,stock=products.filter(p=>p.stock>5).length,low=products.filter(p=>p.stock<=5).length,promos=products.filter(p=>p.promotion).length;
 return shell('Produits',`<section class="admin-kpis admin-product-kpis"><div class="admin-kpi"><small>Produits au total</small><b>${total}</b><span>catalogue</span></div><div class="admin-kpi"><small>En stock</small><b>${stock}</b><span>disponibles</span></div><div class="admin-kpi"><small>Stock faible</small><b>${low}</b><span>à surveiller</span></div><div class="admin-kpi"><small>En promotion</small><b>${promos}</b><span>offres actives</span></div></section><section class="admin-products-card"><div class="admin-toolbar"><input data-admin-search placeholder="Rechercher un produit..."><select data-admin-category><option value="">Toutes les catégories</option>${[...new Set(products.map(p=>p.category).filter(Boolean))].map(c=>`<option>${esc(c)}</option>`).join('')}</select><select data-admin-promo><option value="">Toutes les promotions</option><option value="yes">En promotion</option><option value="no">Sans promotion</option></select><button data-admin-reset>Réinitialiser</button></div><div class="admin-table-wrap"><table class="admin-table admin-products-table"><thead><tr><th>Produit</th><th>Catégorie</th><th>Prix</th><th>Stock</th><th>Promo</th><th>Statut</th><th>Actions</th></tr></thead><tbody>${products.map(p=>productRow(p)).join('')}</tbody></table></div></section>`,'Gérez vos produits et mettez en avant vos offres spéciales.')}
function productRow(p:Product){const disc=Math.max(0,Math.min(90,Number(p.discount_percent)||0));return `<tr data-product-row data-name="${esc(p.name.toLowerCase())}" data-category="${esc(p.category)}" data-promo="${p.promotion?'yes':'no'}"><td><div class="admin-prod"><img src="${esc(p.image_url||'')}" onerror="this.style.display='none'"><div><b>${esc(p.name)}</b><small>${esc(p.description||'')}</small></div></div></td><td>${esc(p.category)}</td><td><b>${money(p.price)}</b></td><td><span class="${p.stock<=5?'stock-low':'stock-ok'}">${p.stock}</span></td><td><div class="promo-control"><button class="promo-switch ${p.promotion?'on':''}" data-safe-promo="${p.id}" aria-label="Promotion"><i></i></button>${p.promotion?`<button class="promo-percent" data-safe-discount="${p.id}">-${disc||10}%</button>`:''}</div></td><td><span class="status-active">● Actif</span></td><td><button class="admin-edit icon-action" data-safe-edit="${p.id}" title="Modifier">✎</button><button class="admin-delete icon-action" data-safe-delete="${p.id}" title="Supprimer">⌫</button></td></tr>`}
function addView(p?:Product){return shell(p?'Modifier produit':'Ajouter produit',`<section class="admin-products-card"><form class="admin-form" data-safe-form data-id="${p?.id||''}"><label>Nom<input name="name" required value="${esc(p?.name||'')}"></label><label>Catégorie<input name="category" value="${esc(p?.category||'')}"></label><label>Prix (DH)<input name="price" type="number" min="0" step="0.01" required value="${p?.price??''}"></label><label>Stock<input name="stock" type="number" min="0" required value="${p?.stock??''}"></label><label>Promotion<select name="promotion"><option value="false" ${!p?.promotion?'selected':''}>Non</option><option value="true" ${p?.promotion?'selected':''}>Oui</option></select></label><label>Réduction (%)<input name="discount_percent" type="number" min="0" max="90" value="${p?.discount_percent??10}"></label><label class="full">Image URL<input name="image_url" value="${esc(p?.image_url||'')}"></label><label class="full">Description<textarea name="description">${esc(p?.description||'')}</textarea></label><div class="admin-form-actions"><button class="admin-primary" type="submit">Enregistrer</button></div></form></section>`)}
function ordersView(){return shell('Commandes',`<section class="admin-products-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Commande</th><th>Client</th><th>Total</th><th>Paiement</th><th>Statut</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${esc(o.reference||`OSR-${o.id}`)}</b><small>${o.created_at?new Date(o.created_at).toLocaleString('fr-FR'):''}</small></td><td>${esc(o.customer?.name||'Client OSRAH')}</td><td>${money(o.total||0)}</td><td>${esc(o.payment_method||'')}</td><td><span class="status-active">${esc(o.status||'Nouvelle')}</span></td></tr>`).join('')}</tbody></table></div></section>`)}
function clientsView(){const map=new Map<string,any>();orders.forEach(o=>{const e=o.customer?.email||o.customer?.phone||o.customer?.name;if(e)map.set(e,o.customer)});return shell('Clients',`<section class="admin-products-card">${[...map.values()].map(c=>`<div class="admin-list-row"><div><b>${esc(c.name||'Client OSRAH')}</b><small>${esc(c.email||'')} ${esc(c.city||'')}</small></div><span class="admin-badge">Client</span></div>`).join('')||'<div class="admin-empty">Aucun client pour le moment.</div>'}</section>`)}
function statsView(){const ca=orders.reduce((s,o)=>s+Number(o.total||0),0);const avg=orders.length?ca/orders.length:0;return shell('Statistiques',`<section class="admin-kpis"><div class="admin-kpi"><small>Chiffre d'affaires</small><b>${money(ca)}</b></div><div class="admin-kpi"><small>Panier moyen</small><b>${money(avg)}</b></div><div class="admin-kpi"><small>Commandes</small><b>${orders.length}</b></div><div class="admin-kpi"><small>Produits</small><b>${products.length}</b></div></section>`)}
async function show(name:string){const m=main();if(!m)return;await load();m.innerHTML=name==='products'?productsView():name==='add'?addView():name==='orders'?ordersView():name==='clients'?clientsView():name==='stats'?statsView():dashboard();decorateSidebar(name)}
function decorateSidebar(active:string){const aside=document.querySelector('.x-admin>aside');if(!aside)return;aside.classList.add('osrah-admin-sidebar');const buttons=Array.from(aside.querySelectorAll(':scope>button'));buttons.forEach((b,i)=>b.classList.toggle('admin-on',['dashboard','products','add','orders','clients','stats'][i]===active));if(!aside.querySelector('.admin-side-note')){const note=document.createElement('div');note.className='admin-side-note';note.innerHTML='<b>♕</b><span>Prendre soin<br>de votre beauté<br>au quotidien</span><em>⌁</em>';aside.insertBefore(note,aside.querySelector('.last'))}}
async function savePromo(p:Product,promotion:boolean,discount=p.discount_percent||10){const body={...p,promotion,discount_percent:discount,active:p.active!==false};const r=await fetch(`${API}/${p.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error();await show('products')}
function applyFilters(){const q=(document.querySelector<HTMLInputElement>('[data-admin-search]')?.value||'').toLowerCase();const cat=document.querySelector<HTMLSelectElement>('[data-admin-category]')?.value||'';const promo=document.querySelector<HTMLSelectElement>('[data-admin-promo]')?.value||'';document.querySelectorAll<HTMLElement>('[data-product-row]').forEach(r=>{const ok=(!q||r.dataset.name?.includes(q))&&(!cat||r.dataset.category===cat)&&(!promo||r.dataset.promo===promo);r.style.display=ok?'':'none'})}

document.addEventListener('click',async e=>{
 const t=e.target as HTMLElement|null;if(!t)return;
 const aside=document.querySelector('.x-admin>aside');
 if(aside&&aside.contains(t)){
  const btn=t.closest('button') as HTMLButtonElement|null;
  if(btn&&btn.parentElement===aside){const buttons=Array.from(aside.querySelectorAll(':scope>button'));const i=buttons.indexOf(btn);const names=['dashboard','products','add','orders','clients','stats'];if(i>=0&&i<6){e.preventDefault();e.stopPropagation();await show(names[i]);return}}
 }
 if(!t.closest('.x-admin'))return;
 if(t.closest('[data-safe-shop]')){const reactShop=document.querySelector('.x-admin>main header button:not([data-safe-shop])') as HTMLButtonElement|null;if(reactShop)reactShop.click();return}
 const edit=t.closest('[data-safe-edit]') as HTMLElement|null;if(edit){const p=products.find(x=>x.id===Number(edit.dataset.safeEdit));const m=main();if(p&&m)m.innerHTML=addView(p);return}
 const del=t.closest('[data-safe-delete]') as HTMLElement|null;if(del){if(!confirm('Supprimer ce produit ?'))return;await fetch(`${API}/${del.dataset.safeDelete}`,{method:'DELETE'}).catch(()=>{});await show('products');return}
 const promo=t.closest('[data-safe-promo]') as HTMLElement|null;if(promo){const p=products.find(x=>x.id===Number(promo.dataset.safePromo));if(!p)return;try{await savePromo(p,!p.promotion)}catch{alert('Impossible de modifier la promotion. Vérifiez le backend.')}return}
 const discount=t.closest('[data-safe-discount]') as HTMLElement|null;if(discount){const p=products.find(x=>x.id===Number(discount.dataset.safeDiscount));if(!p)return;const v=prompt('Pourcentage de réduction (1 à 90)',String(p.discount_percent||10));if(v===null)return;const n=Math.max(1,Math.min(90,Number(v)||10));try{await savePromo(p,true,n)}catch{alert('Impossible de modifier la réduction.')}return}
 if(t.closest('[data-admin-reset]')){const s=document.querySelector<HTMLInputElement>('[data-admin-search]');const c=document.querySelector<HTMLSelectElement>('[data-admin-category]');const p=document.querySelector<HTMLSelectElement>('[data-admin-promo]');if(s)s.value='';if(c)c.value='';if(p)p.value='';applyFilters();return}
},true);

document.addEventListener('input',e=>{const t=e.target as HTMLElement;if(t.matches('[data-admin-search],[data-admin-category],[data-admin-promo]'))applyFilters()},true);
document.addEventListener('change',e=>{const t=e.target as HTMLElement;if(t.matches('[data-admin-category],[data-admin-promo]'))applyFilters()},true);
document.addEventListener('submit',async e=>{const form=(e.target as HTMLElement)?.closest('[data-safe-form]') as HTMLFormElement|null;if(!form)return;e.preventDefault();const fd=new FormData(form);const id=form.dataset.id;const body={name:String(fd.get('name')||''),category:String(fd.get('category')||''),price:Number(fd.get('price')||0),stock:Number(fd.get('stock')||0),image_url:String(fd.get('image_url')||''),description:String(fd.get('description')||''),promotion:String(fd.get('promotion'))==='true',discount_percent:Number(fd.get('discount_percent')||0),active:true};const r=await fetch(id?`${API}/${id}`:API,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).catch(()=>null);if(!r||!r.ok){alert('Impossible d’enregistrer. Vérifiez le backend.');return}await show('products')},true);

window.addEventListener('load',()=>setTimeout(()=>decorateSidebar('dashboard'),100));
