import './admin-premium.css';

type Product={id:number;name:string;description?:string;price:number;stock:number;category:string;image_url?:string};
const API='http://localhost:5000/api/products';
let initialized=false;
let products:Product[]=[];

const money=(n:number)=>`${Number(n||0).toFixed(0)} DH`;
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
async function loadProducts(){try{const r=await fetch(API);products=r.ok?await r.json():[]}catch{products=[]}}
function root(){return document.querySelector('.x-admin') as HTMLElement|null}
function main(){return document.querySelector('.x-admin>main') as HTMLElement|null}

function dashboardHtml(){
 const total=products.length||16;const low=products.filter(p=>Number(p.stock)<=5).length;const value=products.reduce((s,p)=>s+Number(p.price||0)*Number(p.stock||0),0);
 const latest=products.slice(0,5);
 return `<section class="admin-section active" data-admin-section="dashboard"><div class="admin-topbar"><div class="admin-title"><h1>Tableau de bord</h1><p>Vue générale de votre boutique OSRAH Cosmétiques.</p></div><div class="admin-actions"><button class="admin-secondary" data-admin-client>Voir la boutique</button><button class="admin-primary" data-admin-go="add">+ Ajouter un produit</button></div></div><div class="admin-kpis"><div class="admin-kpi"><small>Produits</small><b>${total}</b><span>Catalogue actif</span></div><div class="admin-kpi"><small>Commandes</small><b>3</b><span>À traiter aujourd'hui</span></div><div class="admin-kpi"><small>Chiffre d'affaires</small><b>472 DH</b><span>Démo actuelle</span></div><div class="admin-kpi"><small>Stock faible</small><b>${low}</b><span>Produits à surveiller</span></div></div><div class="admin-grid"><div class="admin-card"><h2>Produits récents</h2>${latest.length?`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Produit</th><th>Catégorie</th><th>Prix</th><th>Stock</th></tr></thead><tbody>${latest.map(p=>`<tr><td><div class="admin-prod"><img src="${esc(p.image_url||'')}" onerror="this.style.display='none'"><b>${esc(p.name)}</b></div></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td><span class="admin-stock ${p.stock<=5?'admin-low':''}">${p.stock}</span></td></tr>`).join('')}</tbody></table></div>`:`<div class="admin-empty">Backend hors ligne ou aucun produit chargé.</div>`}</div><div class="admin-card"><h2>Aperçu gestion</h2><div class="admin-list"><div class="admin-list-row"><div><b>Valeur du stock</b><small>Estimation catalogue</small></div><span class="admin-badge">${money(value)}</span></div><div class="admin-list-row"><div><b>Commandes en attente</b><small>À préparer</small></div><span class="admin-badge">2</span></div><div class="admin-list-row"><div><b>Clients actifs</b><small>Comptes démo</small></div><span class="admin-badge">24</span></div><div class="admin-list-row"><div><b>Promotions</b><small>Produits remisés</small></div><span class="admin-badge">8</span></div></div></div></div></section>`;
}
function productsHtml(){return `<section class="admin-section" data-admin-section="products"><div class="admin-topbar"><div class="admin-title"><h1>Gestion des produits</h1><p>Consultez, modifiez ou supprimez les produits du catalogue.</p></div><button class="admin-primary" data-admin-go="add">+ Ajouter un produit</button></div><div class="admin-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Produit</th><th>Catégorie</th><th>Prix</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${products.map(p=>`<tr><td><div class="admin-prod"><img src="${esc(p.image_url||'')}" onerror="this.style.display='none'"><div><b>${esc(p.name)}</b><small>${esc((p.description||'').slice(0,60))}</small></div></div></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td><span class="admin-stock ${p.stock<=5?'admin-low':''}">${p.stock}</span></td><td><button class="admin-edit" data-admin-edit="${p.id}">Modifier</button><button class="admin-delete" data-admin-delete="${p.id}">Supprimer</button></td></tr>`).join('')}</tbody></table></div>${products.length?'':'<div class="admin-empty">Aucun produit trouvé.</div>'}</div></section>`}
function addHtml(p?:Product){return `<section class="admin-section" data-admin-section="add"><div class="admin-topbar"><div class="admin-title"><h1>${p?'Modifier le produit':'Ajouter un produit'}</h1><p>${p?'Mettez à jour les informations du produit.':'Ajoutez un nouveau produit au catalogue OSRAH.'}</p></div></div><div class="admin-card"><div class="admin-note">Les données sont enregistrées via votre backend local Node/Express.</div><form class="admin-form" data-admin-form data-id="${p?.id||''}"><label>Nom du produit<input name="name" required value="${esc(p?.name||'')}"></label><label>Catégorie<select name="category"><option>Visage</option><option>Corps</option><option>Cheveux</option><option>Solaire</option><option>Parfums</option><option>Homme</option><option>Coffrets</option></select></label><label>Prix (DH)<input name="price" type="number" min="0" step="0.01" required value="${p?.price??''}"></label><label>Stock<input name="stock" type="number" min="0" required value="${p?.stock??''}"></label><label class="full">URL de l'image<input name="image_url" value="${esc(p?.image_url||'')}"></label><label class="full">Description<textarea name="description">${esc(p?.description||'')}</textarea></label><div class="admin-form-actions"><button type="button" class="admin-secondary" data-admin-go="products">Annuler</button><button class="admin-primary" type="submit">${p?'Enregistrer les modifications':'Ajouter le produit'}</button></div></form></div></section>`}
function ordersHtml(){return `<section class="admin-section" data-admin-section="orders"><div class="admin-topbar"><div class="admin-title"><h1>Commandes</h1><p>Suivi des commandes clients.</p></div></div><div class="admin-card"><div class="admin-list"><div class="admin-list-row"><div><b>#OSR-1003 · 224 DH</b><small>Casablanca · Aujourd'hui</small></div><span class="admin-badge">En préparation</span></div><div class="admin-list-row"><div><b>#OSR-1002 · 129 DH</b><small>Rabat · Hier</small></div><span class="admin-badge">Expédiée</span></div><div class="admin-list-row"><div><b>#OSR-1001 · 119 DH</b><small>Mohammedia · 05/09/2026</small></div><span class="admin-badge">Livrée</span></div></div></div></section>`}
function clientsHtml(){return `<section class="admin-section" data-admin-section="clients"><div class="admin-topbar"><div class="admin-title"><h1>Clients</h1><p>Liste et aperçu de vos clients.</p></div></div><div class="admin-card"><div class="admin-list"><div class="admin-list-row"><div><b>Client OSRAH</b><small>client@osrah.ma · Casablanca</small></div><span class="admin-badge">Actif</span></div><div class="admin-list-row"><div><b>Sara M.</b><small>sara@example.com · Rabat</small></div><span class="admin-badge">2 commandes</span></div><div class="admin-list-row"><div><b>Rania J.</b><small>rania@example.com · Casablanca</small></div><span class="admin-badge">1 commande</span></div></div></div></section>`}
function statsHtml(){return `<section class="admin-section" data-admin-section="stats"><div class="admin-topbar"><div class="admin-title"><h1>Statistiques</h1><p>Indicateurs clés de la boutique.</p></div></div><div class="admin-kpis"><div class="admin-kpi"><small>CA démo</small><b>472 DH</b><span>+12% cette semaine</span></div><div class="admin-kpi"><small>Panier moyen</small><b>157 DH</b><span>3 commandes</span></div><div class="admin-kpi"><small>Produits vendus</small><b>6</b><span>Cette période</span></div><div class="admin-kpi"><small>Clients</small><b>24</b><span>Base actuelle</span></div></div><div class="admin-card"><h2>Performance par catégorie</h2><div class="admin-list"><div class="admin-list-row"><b>Corps</b><span class="admin-badge">38%</span></div><div class="admin-list-row"><b>Cheveux</b><span class="admin-badge">31%</span></div><div class="admin-list-row"><b>Visage</b><span class="admin-badge">19%</span></div><div class="admin-list-row"><b>Solaire & Parfums</b><span class="admin-badge">12%</span></div></div></div></section>`}

function show(name:string){document.querySelectorAll('.admin-section').forEach(s=>s.classList.toggle('active',(s as HTMLElement).dataset.adminSection===name));document.querySelectorAll('.x-admin>aside button').forEach(b=>b.classList.remove('admin-on'));const map:any={dashboard:0,products:1,add:2,orders:3,clients:4,stats:5};const btn=document.querySelectorAll('.x-admin>aside button')[map[name]];btn?.classList.add('admin-on')}
async function build(){const m=main();if(!m)return;await loadProducts();m.innerHTML=`<div class="admin-shell">${dashboardHtml()}${productsHtml()}${addHtml()}${ordersHtml()}${clientsHtml()}${statsHtml()}</div>`;bind();show('dashboard')}
function bind(){const r=root();if(!r)return;const side=Array.from(r.querySelectorAll(':scope>aside>button'));const names=['dashboard','products','add','orders','clients','stats'];side.slice(0,6).forEach((b,i)=>b.addEventListener('click',e=>{e.preventDefault();show(names[i])}));r.querySelectorAll('[data-admin-go]').forEach(el=>el.addEventListener('click',()=>show((el as HTMLElement).dataset.adminGo||'dashboard')));r.querySelector('[data-admin-client]')?.addEventListener('click',()=>{const old=side[0];const reactBtn=(main()?.querySelector('header button') as HTMLButtonElement|null);reactBtn?.click();old?.blur()});r.querySelectorAll('[data-admin-delete]').forEach(el=>el.addEventListener('click',async()=>{const id=Number((el as HTMLElement).dataset.adminDelete);if(!confirm('Supprimer ce produit ?'))return;try{await fetch(`${API}/${id}`,{method:'DELETE'});await build();show('products')}catch{alert('Backend indisponible.')}}));r.querySelectorAll('[data-admin-edit]').forEach(el=>el.addEventListener('click',()=>{const p=products.find(x=>x.id===Number((el as HTMLElement).dataset.adminEdit));const old=r.querySelector('[data-admin-section="add"]');if(old&&p){old.outerHTML=addHtml(p);bind();show('add')}}));const form=r.querySelector('[data-admin-form]') as HTMLFormElement|null;form?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const id=form.dataset.id;const body={name:String(fd.get('name')||''),description:String(fd.get('description')||''),price:Number(fd.get('price')||0),stock:Number(fd.get('stock')||0),category:String(fd.get('category')||''),image_url:String(fd.get('image_url')||'')};try{const res=await fetch(id?`${API}/${id}`:API,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error();await build();show('products')}catch{alert('Impossible d’enregistrer. Vérifiez que le backend est lancé sur localhost:5000.')}})}

function init(){if(!root()){initialized=false;return}if(initialized)return;initialized=true;build()}
const obs=new MutationObserver(init);obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('load',init);setTimeout(init,200);
