import './promotion.css';

type Promo={price:number;old:number};
const KEY='osrah-admin-promos';

function read():Record<string,Promo>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function write(x:Record<string,Promo>){localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new Event('osrah-promos-changed'))}
function num(s:string){return Number((s||'').replace(/[^0-9.,]/g,'').replace(',','.'))||0}

function askPrice(title:string,value:string):Promise<string|null>{return new Promise(resolve=>{document.querySelector('.osrah-price-modal')?.remove();const wrap=document.createElement('div');wrap.className='osrah-price-modal';wrap.innerHTML=`<div class="osrah-price-box"><button type="button" class="osrah-price-x">×</button><h3>${title}</h3><input class="osrah-price-input" inputmode="decimal" value="${value}"><div class="osrah-price-actions"><button type="button" class="osrah-price-cancel">Annuler</button><button type="button" class="osrah-price-ok">OK</button></div></div>`;document.body.appendChild(wrap);const input=wrap.querySelector('.osrah-price-input') as HTMLInputElement;setTimeout(()=>{input.focus();input.select()},0);const done=(v:string|null)=>{wrap.remove();resolve(v)};wrap.querySelector('.osrah-price-ok')?.addEventListener('click',()=>done(input.value));wrap.querySelector('.osrah-price-cancel')?.addEventListener('click',()=>done(null));wrap.querySelector('.osrah-price-x')?.addEventListener('click',()=>done(null));wrap.addEventListener('click',e=>{if(e.target===wrap)done(null)});input.addEventListener('keydown',e=>{if(e.key==='Enter')done(input.value);if(e.key==='Escape')done(null)})})}

function enhanceAdmin(){const section=document.querySelector('[data-admin-section="products"]');if(!section)return;const promos=read();section.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(row=>{const name=row.querySelector('.admin-prod b')?.textContent?.trim()||'';if(!name)return;const priceCell=row.children[2] as HTMLElement|undefined;const actions=row.children[4] as HTMLElement|undefined;if(!priceCell||!actions)return;const active=promos[name];if(active)priceCell.innerHTML=`<b style="color:#c72f67">${active.price.toFixed(0)} DH</b><br><del style="color:#9b7b87">${active.old.toFixed(0)} DH</del>`;const existing=actions.querySelector('[data-promo-name]') as HTMLButtonElement|null;if(existing){existing.textContent=active?'Modifier promo':'Mettre en promo';const remove=actions.querySelector('[data-promo-remove]');if(active&&!remove){const r=document.createElement('button');r.type='button';r.className='admin-delete';r.dataset.promoRemove=name;r.textContent='Retirer promo';actions.appendChild(r)}return}const btn=document.createElement('button');btn.type='button';btn.className='admin-edit';btn.dataset.promoName=name;btn.textContent=active?'Modifier promo':'Mettre en promo';actions.appendChild(btn);if(active){const remove=document.createElement('button');remove.type='button';remove.className='admin-delete';remove.dataset.promoRemove=name;remove.textContent='Retirer promo';actions.appendChild(remove)}})}

function applyClient(){const promos=read();document.querySelectorAll<HTMLElement>('.x-grid article').forEach(card=>{const name=card.querySelector('h3')?.textContent?.trim()||'';const promo=promos[name];if(!promo)return;card.classList.add('admin-promo-client');card.dataset.promoOld=`${promo.old.toFixed(0)} DH`;const info=card.querySelector('.info');if(!info)return;const existingPromo=info.querySelector('.promo-price');if(existingPromo){const span=existingPromo.querySelector('span');const del=existingPromo.querySelector('del');if(span)span.textContent=`${promo.price.toFixed(0)} DH`;if(del)del.textContent=`${promo.old.toFixed(0)} DH`;return}const regular=info.querySelector(':scope > b') as HTMLElement|null;if(regular){regular.textContent=`${promo.price.toFixed(0)} DH`;regular.classList.add('admin-promo-price');regular.dataset.old=`${promo.old.toFixed(0)} DH`}});const detail=document.querySelector('.x-detail main');if(detail){const name=detail.querySelector('h1')?.textContent?.trim()||'';const promo=promos[name];if(promo){const h2=detail.querySelector('h2') as HTMLElement|null;if(h2){h2.textContent=`${promo.price.toFixed(2)} DH`;h2.dataset.old=`${promo.old.toFixed(0)} DH`;h2.classList.add('admin-promo-detail')}}}}
function refresh(){enhanceAdmin();applyClient()}

document.addEventListener('click',async e=>{const t=e.target as HTMLElement|null;if(!t)return;const promoBtn=t.closest('[data-promo-name]') as HTMLElement|null;if(promoBtn){e.preventDefault();e.stopPropagation();const name=promoBtn.dataset.promoName||'';const promos=read();const row=promoBtn.closest('tr');const current=promos[name];const base=current?.old||num((row?.children[2] as HTMLElement|null)?.textContent||'');const oldRaw=await askPrice(`Prix normal de ${name} (DH)`,String(base));if(oldRaw===null)return;const old=Number(oldRaw.replace(',','.'));if(!old||old<=0)return alert('Prix normal invalide.');const promoRaw=await askPrice(`Prix promo de ${name} (DH)`,String(current?.price||Math.max(1,Math.round(old*.8))));if(promoRaw===null)return;const price=Number(promoRaw.replace(',','.'));if(!price||price<=0||price>=old)return alert('Le prix promo doit être inférieur au prix normal.');promos[name]={price,old};write(promos);refresh();return}const remove=t.closest('[data-promo-remove]') as HTMLElement|null;if(remove){e.preventDefault();e.stopPropagation();const promos=read();delete promos[remove.dataset.promoRemove||''];write(promos);location.reload();return}setTimeout(refresh,80)},true);
window.addEventListener('load',refresh);window.addEventListener('osrah-promos-changed',refresh);setTimeout(refresh,250);setTimeout(refresh,900);

const style=document.createElement('style');style.textContent=`.osrah-price-modal{position:fixed;inset:0;background:rgba(42,12,25,.38);display:grid;place-items:center;z-index:99999;padding:20px}.osrah-price-box{width:min(520px,92vw);background:#fff;border-radius:22px;padding:28px;box-shadow:0 24px 70px rgba(62,12,32,.22);position:relative}.osrah-price-box h3{margin:0 36px 18px 0;color:#55112c;font-size:20px}.osrah-price-input{width:100%;box-sizing:border-box;border:1px solid #e2ccd5;border-radius:12px;padding:14px 16px;font-size:18px;outline:none}.osrah-price-input:focus{border-color:#bd3568;box-shadow:0 0 0 3px rgba(189,53,104,.12)}.osrah-price-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.osrah-price-actions button,.osrah-price-x{border:0;border-radius:10px;padding:11px 20px;cursor:pointer;font-weight:700}.osrah-price-ok{background:#7b1438;color:#fff}.osrah-price-cancel{background:#f6eaf0;color:#6b2740}.osrah-price-x{position:absolute;right:16px;top:12px;background:transparent;color:#7b1438;font-size:24px;padding:4px 8px}.x-grid article.admin-promo-client{position:relative}.x-grid article.admin-promo-client:before{content:'PROMO';position:absolute;left:14px;top:14px;background:#c72f67;color:#fff;font-size:11px;font-weight:800;padding:7px 10px;border-radius:999px;z-index:4}.admin-promo-price{color:#c72f67!important}.admin-promo-price:after{content:attr(data-old);display:inline-block;margin-left:8px;color:#9b7b87;font-size:12px;font-weight:400;text-decoration:line-through}.admin-promo-detail:after{content:attr(data-old);display:block;color:#9b7b87;font-size:16px;font-weight:400;text-decoration:line-through;margin-top:4px}`;document.head.appendChild(style);
